server {
    listen 80;
    
    # Compressão para deixar o app mais rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Tenta servir o arquivo requisitado, se não achar cai pro index.html (pra suportar as rotas do React)
        try_files $uri $uri/ /index.html;
    }
}
