"""add_pago_column

Revision ID: 3f6a2c81df51
Revises: 25ebe6280a67
Create Date: 2026-07-22 14:32:52.718563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6a2c81df51'
down_revision: Union[str, Sequence[str], None] = '25ebe6280a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gasto_diarios', sa.Column('pago', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gasto_diarios', 'pago')
    # ### end Alembic commands ###
