"""add_dono_to_cartoes

Revision ID: daf5d45e6f60
Revises: e233da8b49a2
Create Date: 2026-07-22 14:07:54.800470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf5d45e6f60'
down_revision: Union[str, Sequence[str], None] = 'e233da8b49a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartoes', sa.Column('dono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartoes', 'dono')
    # ### end Alembic commands ###
