"""create_receitas_table

Revision ID: e233da8b49a2
Revises: 5a37c6cf7ecb
Create Date: 2026-07-22 11:20:01.908316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e233da8b49a2'
down_revision: Union[str, Sequence[str], None] = '5a37c6cf7ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('cartao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receitas_descricao'), 'receitas', ['descricao'], unique=False)
    op.create_index(op.f('ix_receitas_id'), 'receitas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receitas_id'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_descricao'), table_name='receitas')
    op.drop_table('receitas')
    # ### end Alembic commands ###
